apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tinagloege/infrastructure/
    targetRevision: HEAD
    path: deployments
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true
